### ISSUE TITLE
Use FontForge AppImage on Travis CI

### ISSUE THREAD

**Issue by ghost** [probonopd/font-leutkirch#13]
From [`.travis.yml`](https://github.com/probonopd/font-leutkirch/blob/master/.travis.yml):

```
language: minimal
dist: bionic

script:
  - sudo apt-get -y install fontforge
...
```

Why need install DEB's if FontForge available as AppImage?

- https://github.com/fontforge/fontforge/releases/tag/20200314
  - [`FontForge-2020-03-14-67687b0-x86_64.AppImage`](https://github.com/fontforge/fontforge/releases/download/20200314/FontForge-2020-03-14-67687b0-x86_64.AppImage)

**Comment by probonopd** [comment]
Good catch. Possibly we will want to replace FontForge for this task with https://github.com/adobe-type-tools/afdko or other tools that specialize in a scripted build process anyway.

**Comment by ghost** [comment]
> to replace FontForge for this task with other tools that specialize in a scripted build process

What is wrong with FontForge scripting features?

**Comment by probonopd** [comment]
I don't think anything is wrong with it but possibly other tools can do even more because they are _specialized_ for the purpose? (=There must be a reason Adobe is not doing their fonts with FontForge?)

**Comment by ghost** [comment]
> because they are specialized for the purpose?

Is not FontForge is most specialized open-source tool designed to build font files?

> There must be a reason Adobe is not doing their fonts with FontForge?

Adobe always avoid to use any 3rd-party open-source projects.

**Comment by probonopd** [comment]
> Adobe always avoid to use any 3rd-party open-source projects.

Not anymore. At least not the [font team](https://www.adobe.com/products/type/font-team.html).

**Comment by probonopd** [comment]
In fact, a member of the Adobe fonts team wrote a small open source font tool in Python especially for this today. :+1: Makes me happy and grateful. https://github.com/adobe-type-tools/afdko/issues/1130

**Comment by probonopd** [comment]
afdko is now being used.
